In [1]:
['a', 'b', 'c'] + [1, 2, 3]

['a', 'b', 'c', 1, 2, 3]

In [2]:
type(lambda x: x + 1)

function

In [3]:
import numpy

In [4]:
import numpy as np

In [5]:
r = np.arange(0, 36)

In [6]:
r.resize((6,6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [7]:
r[::7]

array([[0, 1, 2, 3, 4, 5]])

In [8]:
r[:, ::7]

array([[ 0],
       [ 6],
       [12],
       [18],
       [24],
       [30]])

In [9]:
r[0:6, ::-7]

array([[ 5],
       [11],
       [17],
       [23],
       [29],
       [35]])

In [10]:
r.reshape(36)[::7]

array([ 0,  7, 14, 21, 28, 35])

In [13]:
r[2:4, 2:4]

array([[14, 15],
       [20, 21]])